<script lang="ts">
	// Generated by https://quicktype.io
	type Movie = {
		film: string;
		genre: string;
		lead_studio: string;
		audience_score_percentage: string;
		profitability: string;
		rotten_tomatoes_percentage: string;
		worldwide_gross: string;
		year: string;
		size: number;
	};

	let items: Movie[] = [];
	let size = 0;
	let rowsPerPage = 10;
	let currentPage = 0;

	$: start = currentPage * rowsPerPage;
	$: end = Math.min(start + rowsPerPage, size);
	$: slice = items;
	$: lastPage = Math.max(Math.ceil(size / rowsPerPage) - 1, 0);

	if (typeof fetch !== 'undefined') {
		fetchAPI();
	}

	function fetchAPI() {
		const url = `http://localhost:5000/movies?page_id=${currentPage + 1}&page_size=${rowsPerPage}`;
		fetch(url)
			.then((response) => response.json())
			.then((json) => {
				items.length = 0;
				items = json;
				size = items[0].size;
			});
	}
</script>

<div class="container-fluid bg-dark text-light vh-100 text-center">
	<div class="row">
		<h1>Movies List</h1>
	</div>
	<div class="row table-responsive">
		<table class="table table-dark table-striped table-bordered table-hover">
			<caption>List of movies</caption>
			<thead>
				<tr>
					<th>#</th>
					<th>Film</th>
					<th>Genre</th>
					<th>Lead Studio</th>
					<th>Audience Score %</th>
					<th>Profitability</th>
					<th>Rotten Tomatoes %</th>
					<th>Worldwide Gross</th>
					<th>Year</th>
				</tr>
			</thead>
			<tbody>
				{#each slice as item, i}
					<tr>
						<th scope="row">{i + 1}</th>
						<td>{item.film}</td>
						<td>{item.genre}</td>
						<td>{item.lead_studio}</td>
						<td>{item.audience_score_percentage}</td>
						<td>{item.profitability}</td>
						<td>{item.rotten_tomatoes_percentage}</td>
						<td>{item.worldwide_gross}</td>
						<td>{item.year}</td>
					</tr>
				{/each}
			</tbody>
			<tfoot>
				<tr>
					<th>#</th>
					<th>Film</th>
					<th>Genre</th>
					<th>Lead Studio</th>
					<th>Audience Score %</th>
					<th>Profitability</th>
					<th>Rotten Tomatoes %</th>
					<th>Worldwide Gross</th>
					<th>Year</th>
				</tr>
			</tfoot>
		</table>
	</div>
	<div class="row">
		<div class="col">
			<span class="align-middle">({start + 1}-{end} of {size})</span>
		</div>
		<div
			class="col mx-5"
			title="First page"
			on:click={() => {
				currentPage = 0;
				fetchAPI();
			}}
			disabled={currentPage === 0}
		>
			<button class="btn btn-secondary">First Page</button>
		</div>
		<div
			class="col mx-5"
			title="Prev page"
			on:click={() => {
				if (currentPage > 0) {
					currentPage--;
					fetchAPI();
				} else {
					currentPage = 0;
				}
			}}
			disabled={currentPage === 0}
		>
			<button class="btn btn-secondary">Previous Page</button>
		</div>
		<div
			class="col mx-5"
			title="Next page"
			on:click={() => {
				if (currentPage < lastPage) {
					currentPage++;
					fetchAPI();
				} else {
					currentPage = lastPage;
				}
			}}
			disabled={currentPage === lastPage}
		>
			<button class="btn btn-secondary">Next Page</button>
		</div>
		<div
			class="col x-5"
			title="Last page"
			on:click={() => {
				currentPage = lastPage;
				fetchAPI();
			}}
			disabled={currentPage === lastPage}
		>
			<button class="btn btn-secondary">Last Page</button>
		</div>
	</div>
</div>
